### ISSUE TITLE
파이썬 버전 내려야하나요?

### ISSUE THREAD

**Issue by blu3fishez** [CDPTeam7/application-and-server#16]
파이썬 버전 내려야하나요?
<img width="261" alt="image" src="https://github.com/lnsqj123/CDPTeam7/assets/65532873/61a111f0-25fd-48bf-95b0-21b2e5213452">

---

 파이썬 버전을 내려야하네요 
![image](https://github.com/lnsqj123/CDPTeam7/assets/65532873/0ebce7d8-aa23-4a51-aeb0-0679a346073d)

_Originally posted by @blu3piece in https://github.com/lnsqj123/CDPTeam7/issues/15#issuecomment-2098363930_

**Comment by blu3piece** [comment]
맥 / 윈도우 간 호환성 문제였습니다.

배포의 경우, GPU 가 있는 리눅스 인스턴스를 사용했고, Pytorch를 직접 설치하여 해결했습니다.
