### ISSUE TITLE
Testing App

### ISSUE THREAD

**Issue by blu3piece** [CDPTeam7/application-and-server#19]
배포가 완료된 앱을 실제로 사용해보며 테스팅을 진행하였고, 아래와 같은 문제점을 발견했습니다. 6월 6일 내로 수정할 예정입니다.

- [x] 회원가입 화면 에서 회원가입 타이틀이 안보임 (상단 패딩필요)
- [x] 내정보 수정에서 수정하기 누르고 들어가서 지역 수정하려고 누르면 옵션 없음 이라고 나옴
- [x] 아이디 비밀번호 모두 Blank 로 설정하고 회원가입하면 가능함
- [x] 공백입력 방지하기
- [x] 알림 탭 없애기
- [x] 로그아웃 기능 구현하기 (내정보 탭)
- [x] 아이디 비밀번호에 regex 처리 및 공백 처리해야 한다
- [x] 서울 강동구 -> 대전 강동구 
- [x] 프로필 화면에서 카메라 촬영하기 버튼이 먹히지 않고, 인식 가능한 얼굴 업로드 버튼을 누르면 카메라 촬영 화면이 열린다.
- [x] 회원가입 화면에서 내 시를 등록하고 내 구를 등록한 후, 내 시를 바꾸어도 내 시가 바뀌지 않는다.

**Comment by blu3piece** [comment]
- [ ] 서울 강동구 -> 대전 강동구 


- [ ] 프로필 화면에서 카메라 촬영하기 버튼이 먹히지 않고, 인식 가능한 얼굴 업로드 버튼을 누르면 카메라 촬영 화면이 열린다.
- [ ] 회원가입 화면에서 내 시를 등록하고 내 구를 등록한 후, 내 시를 바꾸어도 내 시가 바뀌지 않는다.

**Comment by blu3piece** [comment]
@lnsqj123 로부터 받은 답변입니다.


- [ ] 프로필 화면에서 카메라 촬영하기 버튼이 먹히지 않고, 인식 가능한 얼굴 업로드 버튼을 누르면 카메라 촬영 화면이 열린다.
- [ ] 회원가입 화면에서 내 시를 등록하고 내 구를 등록한 후, 내 시를 바꾸어도 내 시가 바뀌지 않는다.

**Comment by blu3piece** [comment]
@lnsqj123 @LeeSeunggyun @blu3piece @jieun4322 

작업 완료했습니다.

[CDPTeam7/application-and-server](https://github.com/CDPTeam7/application-and-server/tree/refactor/test-application)

**Comment by lnsqj123** [comment]
- [ ] 로그인 후, 프로필 수정에 들어가서 텍스트나 버튼을 클릭한 후, 로그아웃을 하고를 반복하다보면 프로필 수정의 X 버튼이 없어지고, 로그인 화면의 아이디/비밀번호를 클릭할 수 없게 됩니다.
